# Generated by Django 4.1.5 on 2024-02-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicedetail",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="appname.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoicedetail",
            name="price",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
